from uuid import uuid4

from backend.database import get_store
from backend.schemas.sos import SosSendRequest
from backend.utils.time import utc_now_iso


class SosService:
    def __init__(self) -> None:
        self.store = get_store()

    async def send_sos(self, uid: str, request: SosSendRequest) -> dict:
        patient = self.store.get_patient(uid, request.patient_id) or {}
        message = request.message or self._default_message(request, patient)
        event = {
            "id": str(uuid4()),
            "patient_id": request.patient_id,
            "triggered_by": request.triggered_by,
            "message": message,
            "location": request.location,
            "timestamp": utc_now_iso(),
            "deliveries": [],
        }
        return self.store.save_sos_event(uid, event)

    def history(self, uid: str) -> list[dict]:
        return self.store.list_sos_events(uid)

    def _default_message(self, request: SosSendRequest, patient: dict) -> str:
        status = request.status or {}
        location = request.location or status.get("location") or "Location unavailable"
        return "\n".join(
            [
                "🚨 NeuroNode AI Emergency Alert",
                "",
                "Patient:",
                str(patient.get("fullName") or patient.get("patient_name") or patient.get("patientName") or "NuroNode Patient"),
                "",
                "Emergency detected.",
                "",
                "Status",
                "",
                f"Stress Level:\n{request.stress if request.stress is not None else status.get('stress', 'Unknown')}",
                "",
                f"Blink:\n{request.blink if request.blink is not None else status.get('blink', 'Unknown')}",
                "",
                f"Heart Rate:\n{request.heart_rate if request.heart_rate is not None else status.get('heartRate', 'Unknown')}",
                "",
                f"Battery:\n{request.battery if request.battery is not None else status.get('battery', 'Unknown')}",
                "",
                f"Time:\n{utc_now_iso()}",
                "",
                f"Location:\n{location}",
                "",
                "Please reach immediately.",
                "",
                "Generated by NeuroNode AI",
            ]
        )
